export { default as ArticleDetails } from './ArticleDetails/ArticleDetails'
export { default as GeneralManagement } from './GeneralManagement/GeneralManagement'
export { default as FindHouseWithLocation } from './FindHouseWithLocation/FindHouseWithLocation'
export { default as Admin } from './Admin/Admin'
export { default as CreateArticle } from './GeneralManagement/CreateArticle/CreateArticle'
export { default as Home } from './Home/Home'
