const prefix = '/api'
const version = '/v1'

export const ApiPathEnum = {
  Article: `${prefix}${version}/articles`,
  Categories: `${prefix}${version}/categories`,
  Comments: `${prefix}${version}/comments`,
  LandlordRequest: `${prefix}${version}/landlord-request`,
  SendCode: `${prefix}${version}/mail/send-passcode`,
  Users: `${prefix}${version}/users`,
  SigninWithFacebook: 'api/v1/auth/facebook',
  SigninWithGoogle: 'api/v1/auth/google',
  Signin: `${prefix}${version}/auth/login`,
  Signup: `${prefix}${version}/auth/register`,
  Verify: `${prefix}${version}/auth/verify`,
  GetUserByRefreshToken: `${prefix}${version}/auth/refresh`,
  ChangePassword: `${prefix}${version}/auth/changePassword`,
  GetAllProvinces: 'api/province',
  GetAllDistricts: 'api/province/district',
  GetAllWards: '/api/province/ward',
  UploadSingleFile: `${prefix}${version}/files/upload`,
  UploadBase64File: `${prefix}${version}/files/uploadBase64`,
  Follow: `${prefix}${version}/follow`,
  UnFollow: `${prefix}${version}/unFollow`,
  Permission: `${prefix}${version}/permissions`,
  Role: `${prefix}${version}/roles`,
  Statistical: `${prefix}${version}/statistical`,
  VerifyArticle: `${prefix}${version}/verifications`,
  GetRecommendations: `${prefix}${version}/articles/getRecommodations`,
  SubCategory: `${prefix}${version}/subcategories`,
  ForgotPassword: `${prefix}${version}/auth/forgotPassword`,
  // GoongMap
  AutoComplete: 'Place/AutoComplete',
  Detail: 'Place/Detail',
  Geocode: 'geocode',
}
